import type { Character, Location } from '@/Types'

const characters: Character[] = [
  { name: "Mario", image: "mario.png", player: 0, stats: {} },
  { name: "Donkey Kong", image: "donkey_kong.png", player: 0, stats: {} },
  { name: "Link", image: "link.png", player: 0, stats: {} },
  { name: "Samus", image: "samus.png", player: 0, stats: {} },
  { name: "Dark Samus", image: "dark_samus.png", player: 0, stats: {} },
  { name: "Yoshi", image: "yoshi.png", player: 0, stats: {} },
  { name: "Kirby", image: "kirby.png", player: 0, stats: {} },
  { name: "Fox", image: "fox.png", player: 0, stats: {} },
  { name: "Pikachu", image: "pikachu.png", player: 0, stats: {} },
  { name: "Luigi", image: "luigi.png", player: 0, stats: {} },
  { name: "Ness", image: "ness.png", player: 0, stats: {} },
  { name: "Captain Falcon", image: "captain_falcon.png", player: 0, stats: {} },
  { name: "Jigglypuff", image: "jigglypuff.png", player: 0, stats: {} },
  { name: "Peach", image: "peach.png", player: 0, stats: {} },
  { name: "Daisy", image: "daisy.png", player: 0, stats: {} },
  { name: "Bowser", image: "bowser.png", player: 0, stats: {} },
  { name: "Ice Climbers", image: "ice_climbers.png", player: 0, stats: {} },
  { name: "Sheik", image: "sheik.png", player: 0, stats: {} },
  { name: "Zelda", image: "zelda.png", player: 0, stats: {} },
  { name: "Dr. Mario", image: "dr_mario.png", player: 0, stats: {} },
  { name: "Pichu", image: "pichu.png", player: 0, stats: {} },
  { name: "Falco", image: "falco.png", player: 0, stats: {} },
  { name: "Marth", image: "marth.png", player: 0, stats: {} },
  { name: "Lucina", image: "lucina.png", player: 0, stats: {} },
  { name: "Young Link", image: "young_link.png", player: 0, stats: {} },
  { name: "Ganondorf", image: "ganondorf.png", player: 0, stats: {} },
  { name: "Mewtwo", image: "mewtwo.png", player: 0, stats: {} },
  { name: "Roy", image: "roy.png", player: 0, stats: {} },
  { name: "Chrom", image: "chrom.png", player: 0, stats: {} },
  { name: "Mr. Game & Watch", image: "mr_game_and_watch.png", player: 0, stats: {} },
  { name: "Meta Knight", image: "meta_knight.png", player: 0, stats: {} },
  { name: "Pit", image: "pit.png", player: 0, stats: {} },
  { name: "Dark Pit", image: "dark_pit.png", player: 0, stats: {} },
  { name: "Zero Suit Samus", image: "zero_suit_samus.png", player: 0, stats: {} },
  { name: "Wario", image: "wario.png", player: 0, stats: {} },
  { name: "Snake", image: "snake.png", player: 0, stats: {} },
  { name: "Ike", image: "ike.png", player: 0, stats: {} },
  { name: "Pokemon Trainer", image: "pokemon_trainer.png", player: 0, stats: {} },
  { name: "Diddy Kong", image: "diddy_kong.png", player: 0, stats: {} },
  { name: "Lucas", image: "lucas.png", player: 0, stats: {} },
  { name: "Sonic", image: "sonic.png", player: 0, stats: {} },
  { name: "King Dedede", image: "king_dedede.png", player: 0, stats: {} },
  { name: "Olimar", image: "olimar.png", player: 0, stats: {} },
  { name: "Lucario", image: "lucario.png", player: 0, stats: {} },
  { name: "R.O.B.", image: "rob.png", player: 0, stats: {} },
  { name: "Toon Link", image: "toon_link.png", player: 0, stats: {} },
  { name: "Wolf", image: "wolf.png", player: 0, stats: {} },
  { name: "Villager", image: "villager.png", player: 0, stats: {} },
  { name: "Mega Man", image: "mega_man.png", player: 0, stats: {} },
  { name: "Wii Fit Trainer", image: "wii_fit_trainer.png", player: 0, stats: {} },
  { name: "Rosalina & Luma", image: "rosalina_and_luma.png", player: 0, stats: {} },
  { name: "Little Mac", image: "little_mac.png", player: 0, stats: {} },
  { name: "Greninja", image: "greninja.png", player: 0, stats: {} },
  { name: "Palutena", image: "palutena.png", player: 0, stats: {} },
  { name: "Pac-Man", image: "pac_man.png", player: 0, stats: {} },
  { name: "Robin", image: "robin.png", player: 0, stats: {} },
  { name: "Shulk", image: "shulk.png", player: 0, stats: {} },
  { name: "Bowser Jr.", image: "bowser_jr.png", player: 0, stats: {} },
  { name: "Duck Hunt", image: "duck_hunt.png", player: 0, stats: {} },
  { name: "Ryu", image: "ryu.png", player: 0, stats: {} },
  { name: "Ken", image: "ken.png", player: 0, stats: {} },
  { name: "Cloud", image: "cloud.png", player: 0, stats: {} },
  { name: "Corrin", image: "corrin.png", player: 0, stats: {} },
  { name: "Bayonetta", image: "bayonetta.png", player: 0, stats: {} },
  { name: "Inkling", image: "inkling.png", player: 0, stats: {} },
  { name: "Ridley", image: "ridley.png", player: 0, stats: {} },
  { name: "Simon", image: "simon.png", player: 0, stats: {} },
  { name: "Richter", image: "richter.png", player: 0, stats: {} },
  { name: "King K. Rool", image: "king_k_rool.png", player: 0, stats: {} },
  { name: "Isabelle", image: "isabelle.png", player: 0, stats: {} },
  { name: "Incineroar", image: "incineroar.png", player: 0, stats: {} },
  { name: "Piranha Plant", image: "piranha_plant.png", player: 0, stats: {} },
  { name: "Joker", image: "joker.png", player: 0, stats: {} },
  { name: "Hero", image: "hero.png", player: 0, stats: {} },
  { name: "Banjo & Kazooie", image: "banjo_and_kazooie.png", player: 0, stats: {} },
  { name: "Terry", image: "terry.png", player: 0, stats: {} },
  { name: "Byleth", image: "byleth.png", player: 0, stats: {} },
  { name: "Min Min", image: "min_min.png", player: 0, stats: {} },
  { name: "Steve", image: "steve.png", player: 0, stats: {} },
  { name: "Sephiroth", image: "sephiroth.png", player: 0, stats: {} },
  { name: "Pyra/Mythra", image: "pyra_mythra.png", player: 0, stats: {} },
  { name: "Kazuya", image: "kazuya.png", player: 0, stats: {} },
  { name: "Sora", image: "sora.png", player: 0, stats: {} },
  { name: "Mii Brawler", image: "mii_brawler.png", player: 0, stats: {} },
  { name: "Mii Swordfighter", image: "mii_swordfighter.png", player: 0, stats: {} },
  { name: "Mii Gunner", image: "mii_gunner.png", player: 0, stats: {} },
  { name: "Random", image: "random.png", player: 0, stats: {} }
]

const locations:Location[] = [
  { name: "Battlefield", image: "battlefield.png", stats: {} },
  { name: "Small Battlefield", image: "small_battlefield.png", stats: {} },
  { name: "Big Battlefield", image: "big_battlefield.png", stats: {} },
  { name: "Final Destination", image: "final_destination.png", stats: {} },
  { name: "Peach's Castle", image: "peachs_castle.png", stats: {} },
  { name: "Kongo Jungle", image: "kongo_jungle.png", stats: {} },
  { name: "Hyrule Castle", image: "hyrule_castle.png", stats: {} },
  { name: "Super Happy Tree", image: "super_happy_tree.png", stats: {} },
  { name: "Dream Land", image: "dream_land.png", stats: {} },
  { name: "Saffron City", image: "saffron_city.png", stats: {} },
  { name: "Mushroom Kingdom", image: "mushroom_kingdom.png", stats: {} },
  { name: "Princess Peach's Castle", image: "princess_peachs_castle.png", stats: {} },
  { name: "Rainbow Cruise", image: "rainbow_cruise.png", stats: {} },
  { name: "Kongo Falls", image: "kongo_falls.png", stats: {} },
  { name: "Jungle Japes", image: "jungle_japes.png", stats: {} },
  { name: "Great Bay", image: "great_bay.png", stats: {} },
  { name: "Temple", image: "temple.png", stats: {} },
  { name: "Brinstar", image: "brinstar.png", stats: {} },
  { name: "Yoshi's Story", image: "yoshis_story.png", stats: {} },
  { name: "Fountain of Dreams", image: "fountain_of_dreams.png", stats: {} },
  { name: "Green Greens", image: "green_greens.png", stats: {} },
  { name: "Corneria", image: "corneria.png", stats: {} },
  { name: "Venom", image: "venom.png", stats: {} },
  { name: "Pokémon Stadium", image: "pokemon_stadium.png", stats: {} },
  { name: "Onett", image: "onett.png", stats: {} },
  { name: "Mushroom Kingdom II", image: "mushroom_kingdom_ii.png", stats: {} },
  { name: "Brinstar Depths", image: "brinstar_depths.png", stats: {} },
  { name: "Big Blue", image: "big_blue.png", stats: {} },
  { name: "Fourside", image: "fourside.png", stats: {} },
  { name: "Delfino Plaza", image: "delfino_plaza.png", stats: {} },
  { name: "Mushroomy Kingdom", image: "mushroomy_kingdom.png", stats: {} },
  { name: "Figure-8 Circuit", image: "figure_8_circuit.png", stats: {} },
  { name: "WarioWare, Inc.", image: "warioware_inc.png", stats: {} },
  { name: "Bridge of Eldin", image: "bridge_of_eldin.png", stats: {} },
  { name: "Norfair", image: "norfair.png", stats: {} },
  { name: "Frigate Orpheon", image: "frigate_orpheon.png", stats: {} },
  { name: "Yoshi's Island", image: "yoshis_island.png", stats: {} },
  { name: "Halberd", image: "halberd.png", stats: {} },
  { name: "Lylat Cruise", image: "lylat_cruise.png", stats: {} },
  { name: "Pokémon Stadium 2", image: "pokemon_stadium_2.png", stats: {} },
  { name: "Port Town Aero Dive", image: "port_town_aero_dive.png", stats: {} },
  { name: "Castle Siege", image: "castle_siege.png", stats: {} },
  { name: "Distant Planet", image: "distant_planet.png", stats: {} },
  { name: "Smashville", image: "smashville.png", stats: {} },
  { name: "New Pork City", image: "new_pork_city.png", stats: {} },
  { name: "Summit", image: "summit.png", stats: {} },
  { name: "Skyworld", image: "skyworld.png", stats: {} },
  { name: "Shadow Moses Island", image: "shadow_moses_island.png", stats: {} },
  { name: "Luigi's Mansion", image: "luigis_mansion.png", stats: {} },
  { name: "Pirate Ship", image: "pirate_ship.png", stats: {} },
  { name: "Spear Pillar", image: "spear_pillar.png", stats: {} },
  { name: "Mario Bros.", image: "mario_bros.png", stats: {} },
  { name: "Hanenbow", image: "hanenbow.png", stats: {} },
  { name: "Green Hill Zone", image: "green_hill_zone.png", stats: {} },
  { name: "3D Land", image: "3d_land.png", stats: {} },
  { name: "Golden Plains", image: "golden_plains.png", stats: {} },
  { name: "Paper Mario", image: "paper_mario.png", stats: {} },
  { name: "Gerudo Valley", image: "gerudo_valley.png", stats: {} },
  { name: "Spirit Train", image: "spirit_train.png", stats: {} },
  { name: "Dream Land GB", image: "dream_land_gb.png", stats: {} },
  { name: "Unova Pokémon League", image: "unova_pokemon_league.png", stats: {} },
  { name: "Prism Tower", image: "prism_tower.png", stats: {} },

  { name: "Magicant", image: "magicant.png", stats: {} },
  { name: "Arena Ferox", image: "arena_ferox.png", stats: {} },
  { name: "Reset Bomb Forest", image: "reset_bomb_forest.png", stats: {} },
  { name: "Tortimer Island", image: "tortimer_island.png", stats: {} },
  { name: "Balloon Fight", image: "balloon_fight.png", stats: {} },
  { name: "Living Room", image: "living_room.png", stats: {} },
  { name: "Find Mii", image: "find_mii.png", stats: {} },
  { name: "Tomodachi Life", image: "tomodachi_life.png", stats: {} },
  { name: "PictoChat 2", image: "pictochat_2.png", stats: {} },
  { name: "Mushroom Kingdom U", image: "mushroom_kingdom_u.png", stats: {} },
  { name: "Mario Galaxy", image: "mario_galaxy.png", stats: {} },
  { name: "Mario Circuit", image: "mario_circuit.png", stats: {} },
  { name: "Skyloft", image: "skyloft.png", stats: {} },
  { name: "The Great Cave Offensive", image: "great_cave_offensive.png", stats: {} },
  { name: "Kalos Pokémon League", image: "kalos_pokemon_league.png", stats: {} },
  { name: "Coliseum", image: "coliseum.png", stats: {} },
  { name: "Flat Zone X", image: "flat_zone_x.png", stats: {} },
  { name: "Palutena's Temple", image: "palutenas_temple.png", stats: {} },
  { name: "Gamer", image: "gamer.png", stats: {} },
  { name: "Garden of Hope", image: "garden_of_hope.png", stats: {} },
  { name: "Town and City", image: "town_and_city.png", stats: {} },
  { name: "Wii Fit Studio", image: "wii_fit_studio.png", stats: {} },
  { name: "Boxing Ring", image: "boxing_ring.png", stats: {} },
  { name: "Gaur Plain", image: "gaur_plain.png", stats: {} },
  { name: "Duck Hunt", image: "duck_hunt.png", stats: {} },
  { name: "Wrecking Crew", image: "wrecking_crew.png", stats: {} },
  { name: "Pilotwings", image: "pilotwings.png", stats: {} },
  { name: "Wuhu Island", image: "wuhu_island.png", stats: {} },
  { name: "Windy Hill Zone", image: "windy_hill_zone.png", stats: {} },
  { name: "Wily Castle", image: "wily_castle.png", stats: {} },
  { name: "PAC-LAND", image: "pac_land.png", stats: {} },
  { name: "Super Mario Maker", image: "super_mario_maker.png", stats: {} },
  { name: "Suzaku Castle", image: "suzaku_castle.png", stats: {} },
  { name: "Midgar", image: "midgar.png", stats: {} },
  { name: "Umbra Clock Tower", image: "umbra_clock_tower.png", stats: {} },
  { name: "New Donk City Hall", image: "new_donk_city_hall.png", stats: {} },
  { name: "Great Plateau Tower", image: "great_plateau_tower.png", stats: {} },
  { name: "Moray Towers", image: "moray_towers.png", stats: {} },
  { name: "Dracula's Castle", image: "draculas_castle.png", stats: {} },
  { name: "Mementos", image: "mementos.png", stats: {} },
  { name: "Yggdrasil's Altar", image: "yggdrasils_altar.png", stats: {} },
  { name: "Spiral Mountain", image: "spiral_mountain.png", stats: {} },
  { name: "King of Fighters Stadium", image: "king_of_fighters_stadium.png", stats: {} },
  { name: "Garreg Mach Monastery", image: "garreg_mach_monastery.png", stats: {} },
  { name: "Spring Stadium", image: "spring_stadium.png", stats: {} },
  { name: "Minecraft World", image: "minecraft_world.png", stats: {} },
  { name: "Northern Cave", image: "northern_cave.png", stats: {} },
  { name: "Cloud Sea of Alrest", image: "cloud_sea_of_alrest.png", stats: {} },
  { name: "Mishima Dojo", image: "mishima_dojo.png", stats: {} },
  { name: "Hollow Bastion", image: "hollow_bastion.png", stats: {} }
]

export function useDeckData() {
  return {
    characters,
    locations
  }
}
